[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r server/requirements.txt"]

[start]
cmd = "cd server && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"
